name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run ESLint & Prettier
        run: yarn run lint

  testBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build

  build:
    runs-on: ubuntu-latest
    needs: [lint, testBuild]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "O.A.F."
          git config user.email "<>"
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Switch to release branch
        run: |
          git fetch --all
          if git branch | grep -e '^release$'; then git switch release; else git switch --orphan release; fi
      - name: Commit built Mafia files
        run: |
          git add KoLmafia/
          {
            git commit -m "Build Mafia files for commit $GITHUB_SHA"
            git push origin release
          } || exit 0
